### ISSUE TITLE
Make it work on IE Mobile

### ISSUE THREAD

**Issue by floriansegginger** [literallycanvas/literallycanvas#99]
Currently, touch events on the canvas result in scrolling on IE mobile.

The fix is relatively simple, and can be found on this page:
http://blogs.msdn.com/b/ie/archive/2011/10/19/handling-multi-touch-and-mouse-input-in-all-browsers.aspx

All you have to do is add 

``` css
#touchTarget {
-ms-touch-action: none;
}
```

To the canvas, which will disable all default event actions from occuring.
